name: generator
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/FelixCpp/dependency_doc_generator

environment:
  sdk: ^3.4.4

dependencies:
  dart_pubspec_licenses: ^3.0.1
  logger: ^2.4.0
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  parameterized_test: ^2.0.0
  test: ^1.24.0
