name: markdown_writer
description: A library to write markdown files.
version: 1.0.0
repository: https://github.com/FelixCpp/markdown_writer

environment:
  sdk: ^3.4.4

dev_dependencies:
  lints: ^3.0.0
  parameterized_test: ^2.0.0
  test: ^1.24.0
